version: "3.9"
services:
  njs:
    build: ./njs
    # ports:
    #   - "3000:3000"
    environment:
      APP_DOCKER: True
    env_file:
      - ./njs/.env
    restart: always
  rsignals:
    build: ./rsignals
    # ports:
    #   - "8080:8080"
    environment:
      APP_DOCKER: True
    env_file:
      - ./njs/.env
    # see https://docs.docker.com/config/containers/start-containers-automatically/ & https://www.baeldung.com/ops/docker-compose-restart-policies
    restart: always
