version: "3.9"
services:
   p-data:
     build:
       context: ./
       target: program
     container_name: pstats
     restart: on-failure:5
     environment:
       - PYTHONUNBUFFERED=1
     env_file:
       - ./.env
